def is_land_related_english(text):
    """Checks if the given text (in English) contains land-related keywords."""
    english_land_keywords = [
        "land", "surveyor", "processor", "survey", "territory", "boundary", "ownership", "property", "real estate", "accessor",
        "deed of sale", "title deed", "zoning", "processing", "parcel", "lot", "terrain", "geodetic", "land title transfer",
        "topography", "coordinates", "gis", "easement", "tenure", "leasehold", "freehold",
        "subdivision", "appraisal", "mortgage", "escrow", "cadastral", "geospatial", "dispute",
        "land use", "notary", "affidavit", "forestry", "conservation",
        "survey marker", "land grant", "land registry", "demarcation", "surveying instruments",
        "mapping", "cartography", "site development", "land reclamation", "environmental impact",
        "hydrography", "title insurance", "heritage land",
        "right of way", "geological survey", "land tenure system", "land valuation",
        "site planning", "land tenure security", "property assessment", "legal description",
        "land act", "urban planning", "rural land", "municipal planning", "land ownership transfer",
        "taxation of land", "land development", "land acquisition", "land leasing", "survey regulations",
        "electronic certificate authorizing registration", "ecar", "deed of donation", "deed of adjudication", "real property tax", "rpt",
        "capital gains tax", "cgt", "documentary stamp tax", "dst", "transfer tax", "estate tax", "special assessment tax", "zonal valuation", "zv", "blueprint",
        "land patent", "building permit", "occupancy permit", "land clearance", "tax declaration",
        "land claim", "land dispute", "land conflict", "agrarian reform", "land reform",
        "condominium", "townhouse", "commercial land", "agricultural land", "industrial land", "residential land",
        "land management", "land administration", "land policy", "land law", "land information system",
        "land technology", "land education", "land consultation", "land expert", "land organization",
        "property rights", "property obligations", "land transactions", "sales agreement", "lease agreement",
        "property tax payment", "title update", "title verification", "land investigation", "land dispute settlement",
        "land mediation", "land arbitration", "land litigation", "informal settlers", "housing program",
        "land price", "land market", "land investment", "buy land", "sell land",
        "subdivision development", "building construction", "agricultural development", "land mining",
        "land tourism", "land environmental protection", "land preservation", "sustainable land development",
        "land rehabilitation", "land reclassification", "land consolidation", "land division",
        "land exchange", "land donation", "land inheritance", "land distribution", "special land project",
        "land reform program", "land community", "land cooperative", "landowners association",
        "land use planning", "zoning ordinance", "building code", "environmental regulations",
        "infrastructure regulations", "land public services", "public access to land", "private land",
        "public land", "national heritage land", "ancestral domain", "indigenous land rights",
        "land governance", "land economics", "land survey instruments", "aerial survey", "geodetic survey",
        "topographic survey", "hydrographic survey", "boundary survey", "parcellary survey", "relocation survey",
        "as-built survey", "construction survey", "mine survey", "forest survey", "cadastral survey map",
        "georeferencing", "rectification survey", "consolidation-subdivision survey", "strata survey",
        "geographic information science", "remote sensing", "photogrammetry", "gps survey", "total station",
        "theodolite", "leveling instrument", "survey field notes", "survey report", "survey plan",
        "land development plan", "site plan", "master plan", "urban development plan", "regional development plan",
        "environmental management plan", "social impact assessment", "economic feasibility study",
        "land appraisal report", "property valuation report", "market analysis report", "highest and best use",
        "cost approach", "sales comparison approach", "income capitalization approach", "depreciation", "obsolescence",
        "fair market value", "assessed value", "taxable value", "market rent", "capitalization rate",
        "discount rate", "net operating income", "gross rental income", "vacancy rate", "operating expenses",
        "loan-to-value ratio", "debt service coverage ratio", "return on investment", "internal rate of return",
        "equity multiple", "cash flow", "leverage", "yield", "amortization", "foreclosure", "eviction",
        "lease agreement terms", "rental agreement", "property management", "homeowners association", "condo association"
    ]
    lowered_text = text.lower()
    return any(keyword in lowered_text for keyword in english_land_keywords)

def is_land_related_bisaya(text):
    """Checks if the given text (in Bisaya) contains land-related keywords."""
    bisaya_land_keywords = [
        "yuta", "sukod", "tigsukod", "proseso", "teritoryo", "utlanan", "panag-iya", "propyedad", "real estate", "aksesor",
        "deed of sale", "titulo", "zoning", "pagproseso", "parsela", "lote", "tereyn", "geodetic", "pagbalhin sa titulo sa yuta",
        "topograpiya", "koordinasyon", "gis", "easement", "tenure", "leasehold", "freehold",
        "subdibisyon", "appraisal", "mortgage", "escrow", "kadastral", "geospatial", "panagbangi",
        "gamit sa yuta", "notaryo", "affidavit", "forestry", "konserbasyon",
        "marker sa survey", "grant sa yuta", "rehistro sa yuta", "demarkasyon", "instrumento sa pagsukod",
        "mapping", "cartography", "site development", "land reclamation", "epekto sa kalikopan",
        "hydrography", "insurance sa titulo", "kabilin nga yuta",
        "right of way", "geological survey", "sistema sa pagpanag-iya sa yuta", "pagbanabana sa yuta",
        "pagplano sa site", "seguridad sa pagpanag-iya sa yuta", "assessment sa propyedad", "legal nga deskripsyon",
        "balaod sa yuta", "urban planning", "rural nga yuta", "municipal planning", "pagbalhin sa pagpanag-iya sa yuta",
        "buhis sa yuta", "pagpalambo sa yuta", "pag-angkon sa yuta", "pag-abang sa yuta", "regulasyon sa survey",
        "electronic certificate authorizing registration", "ecar", "deed of donation", "deed of adjudication", "real property tax", "rpt",
        "capital gains tax", "cgt", "documentary stamp tax", "dst", "transfer tax", "estate tax", "special assessment tax", "zonal valuation", "zv", "blueprint",
        "blueprint sa yuta", "plano sa yuta", "sertipiko sa titulo", "patent sa yuta", "permiso sa pagtukod",
        "pagbakante sa yuta", "pag-okupar sa yuta", "pag-claim sa yuta", "pag-aplay sa titulo", "opisina sa rehistro sa mga buhatan",
        "buhatan sa assessor", "buhatan sa zoning", "buhatan sa plano", "surveyor general", "mga lagda sa yuta",
        "mga balaod sa propyedad", "mga katungod sa propyedad", "mga obligasyon sa propyedad", "transaksyon sa yuta",
        "kasabutan sa pagbaligya", "kontrata sa pag-abang", "pagbayad sa buhis sa propyedad", "pag-update sa titulo",
        "pag-verify sa titulo", "pag-imbestiga sa yuta", "pag-areglo sa panagbangi sa yuta", "mediasyon sa yuta",
        "arbitrasyon sa yuta", "litigasyon sa yuta", "pag-ebakwit sa mga informal settler", "programang pabahay",
        "presyo sa yuta", "merkado sa yuta", "puhunan sa yuta", "pagpalit ug yuta", "pagbaligya ug yuta",
        "pag-develop ug subdivision", "pagtukod sa ibabaw sa yuta", "pag-ugmad sa agrikultura", "pagmina sa yuta",
        "turismo sa yuta", "proteksyon sa kinaiyahan sa yuta", "pagpreserba sa yuta", "sustainable development sa yuta",
        "rehabilitasyon sa yuta", "pagbag-o sa klasipikasyon sa yuta", "pagkonsolida sa yuta", "pagbahin sa yuta",
        "pag-ilis sa yuta", "donasyon sa yuta", "kabilin sa yuta", "pag-apod-apod sa yuta", "espesyal nga proyekto sa yuta",
        "programa sa reporma sa yuta", "komunidad sa yuta", "kooperatiba sa yuta", "asosasyon sa mga tag-iya sa yuta",
        "pagplano sa paggamit sa yuta", "ordinansa sa zoning", "kodigo sa pagtukod", "mga regulasyon sa kinaiyahan",
        "mga balaod sa imprastraktura", "mga serbisyo publiko sa yuta", "access sa publiko sa yuta", "private nga yuta",
        "publikong yuta", "nasudnong kabilin nga yuta", "ancestral domain", "katutubong katungod sa yuta",
        "pagdumala sa yuta", "administrasyon sa yuta", "polisya sa yuta", "balaod sa yuta", "sistema sa impormasyon sa yuta",
        "teknolohiya sa yuta", "edukasyon sa yuta", "konsultasyon sa yuta", "eksperto sa yuta", "organisasyon sa yuta",
        "instrumento sa pagsukod sa yuta", "aerial survey", "geodetic survey", "topographic survey",
        "hydrographic survey", "boundary survey", "parcellary survey", "relocation survey",
        "as-built survey", "construction survey", "mine survey", "forest survey", "cadastral survey map",
        "georeferencing", "rectification survey", "consolidation-subdivision survey", "strata survey",
        "geographic information science", "remote sensing", "photogrammetry", "gps survey", "total station",
        "theodolite", "leveling instrument", "survey field notes", "survey report", "survey plan",
        "plano sa pagpalambo sa yuta", "plano sa site", "master plan", "plano sa pagpalambo sa urban",
        "plano sa pagpalambo sa rehiyon", "plano sa pagdumala sa kinaiyahan", "social impact assessment",
        "pagtuon sa posibilidad sa ekonomiya", "report sa pagbanabana sa yuta", "report sa pagbanabana sa propyedad",
        "report sa pag-analisar sa merkado", "labing taas ug labing maayo nga paggamit", "pamaagi sa gasto",
        "pamaagi sa pagtandi sa halin", "pamaagi sa pag-capitalize sa kita", "depresasyon", "obsolescence",
        "takos nga bili sa merkado", "gibanabana nga bili", "bili nga buhis", "abang sa merkado", "rate sa kapitalisasyon",
        "discount rate", "net operating income", "gross rental income", "vacancy rate", "mga galastuhan sa operasyon",
        "loan-to-value ratio", "debt service coverage ratio", "return on investment", "internal rate of return",
        "equity multiple", "cash flow", "leverage", "yield", "amortization", "foreclosure", "pagpalayas",
        "mga termino sa kasabutan sa pag-abang", "kasabutan sa pag-abang", "pagdumala sa propyedad",
        "asosasyon sa mga tag-iya sa balay", "asosasyon sa condo", "babae"
    ]
    lowered_text = text.lower()
    return any(keyword in lowered_text for keyword in bisaya_land_keywords)